import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import Loader from "@/components/shared/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ClerkLoading >
            <div className="text-center w-full h-screen flex items-center justify-center text-3xl">
              <Loader/>
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <Provider>
              {children}
            </Provider>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
